run:
  timeout: 5m
  skip-dirs:
    - tests/e2e
linters:
  enable:
    - gofmt
    - goimports
    - revive
    - govet
    - staticcheck
    - unused
    - ineffassign
    - typecheck
    - errcheck
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck